package com.sap.cds.feature.attachments.utilities;

import org.slf4j.Marker;
import org.slf4j.MarkerFactory;

public enum LoggingMarker {

	ATTACHMENT_SERVICE_REGISTRATION,

	APPLICATION_CREATE_HANDLER,	APPLICATION_UPDATE_HANDLER,	APPLICATION_DELETE_HANDLER,	APPLICATION_READ_HANDLER,

	DRAFT_PATCH_HANDLER,	DRAFT_CANCEL_HANDLER,

	ATTACHMENT_SERVICE_CREATE_METHOD,	ATTACHMENT_SERVICE_DELETE_METHOD,	ATTACHMENT_SERVICE_RESTORE_DELETE_METHOD,	ATTACHMENT_SERVICE_READ_METHOD,

	ATTACHMENT_SERVICE_CREATE_HANDLER,	ATTACHMENT_SERVICE_DELETE_HANDLER,	ATTACHMENT_SERVICE_RESTORE_DELETE_HANDLER,	ATTACHMENT_SERVICE_READ_HANDLER;

	public Marker getMarker() {
		return MarkerFactory.getMarker(name());
	}

}
