name: Deploy Release to Maven Central
description: "Deploys released artifacts to Maven Central repository."

inputs:
  user:
    description: "The user used for the upload (technical user for maven central upload)"
    required: true
  password:
    description: "The password used for the upload (technical user for maven central upload)"
    required: true
  pgp-pub-key:
    description: "The public pgp key ID"
    required: true
  pgp-private-key:
    description: "The private pgp key"
    required: true
  pgp-passphrase:
    description: "The passphrase for pgp"
    required: true
  revision:
    description: "The revision of cds-feature-attachments"
    required: true
  maven-version:
    description: "The Maven version the build shall run with."
    required: true

runs:
  using: composite
  steps:
    - name: Echo Inputs
      run: |
        echo "user: ${{ inputs.user }}"
        echo "revision: ${{ inputs.revision }}"
      shell: bash

    - name: Set up Java 
      uses: actions/setup-java@v4
      with:
        distribution: sapmachine
        java-version: '17'
        cache: maven
        server-id: central
        server-username: MAVEN_CENTRAL_USER
        server-password: MAVEN_CENTRAL_PASSWORD

    - name: Set up Maven ${{ inputs.maven-version }}
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: ${{ inputs.maven-version }}

    - name: Import GPG Key
      run: |
        echo "${{ inputs.pgp-private-key }}" | gpg --batch --passphrase "$PASSPHRASE" --import
      shell: bash  
      env:
        PASSPHRASE: ${{ inputs.pgp-passphrase }}

    - name: Deploy to Maven Central
      run: >
        mvn -B -ntp -fae --show-version
        -Dmaven.install.skip=true
        -Dmaven.test.skip=true
        -Dgpg.passphrase="$GPG_PASSPHRASE"
        -Dgpg.keyname="$GPG_PUB_KEY"
        -Drevision="${{ inputs.revision }}"
        deploy
      shell: bash
      env:
        MAVEN_CENTRAL_USER: ${{ inputs.user }}
        MAVEN_CENTRAL_PASSWORD: ${{ inputs.password }}
        GPG_PASSPHRASE: ${{ inputs.pgp-passphrase }}
        GPG_PUB_KEY: ${{ inputs.pgp-pub-key }}
