name: Maven Release
description: "Deploys a Maven package to Maven Central repository."

inputs:
  user:
    description: "The user used for the upload (technical user for maven central upload)"
    required: true
  password:
    description: "The password used for the upload (technical user for maven central upload)"
    required: true
  profile:
    description: "The profile id"
    required: true
  pgp-pub-key:
    description: "The public pgp key ID"
    required: true
  pgp-private-key:
    description: "The private pgp key"
    required: true
  pgp-passphrase:
    description: "The passphrase for pgp"
    required: true
  pom-file:
    description: "The path to the POM file."
    required: false
    default: "pom.xml"

runs:
  using: composite
  steps:
    - name: "Echo Inputs"
      run: |
        echo "user: ${{ inputs.user }}"
        echo "profile: ${{ inputs.profile }}"
        echo "pom-file: ${{ inputs.pom-file }}"
      shell: bash

    - name: "Setup Java"
      uses: actions/setup-java@v4
      with:
        distribution: 'sapmachine'
        java-version: '17'
        server-id: ossrh
        server-username: MAVEN_CENTRAL_USER
        server-password: MAVEN_CENTRAL_PASSWORD

    - name: "Import GPG Key"
      run: |
        echo "${{ inputs.pgp-private-key }}" | gpg --batch --passphrase "$PASSPHRASE" --import
      shell: bash  
      env:
        PASSPHRASE: ${{ inputs.pgp-passphrase }}

    - name: "Deploy Locally"
      run: >
        mvn
        --batch-mode
        --no-transfer-progress
        --fail-at-end
        --threads 1C
        --show-version
        -DaltDeploymentRepository=local::default::file://${{ github.workspace }}/temp_local_repo
        -Dmaven.install.skip=true
        -Dmaven.test.skip=true
        -f ${{ inputs.pom-file }}
        -Dgpg.passphrase="$GPG_PASSPHRASE"
        -Dgpg.keyname="$GPG_PUB_KEY"
        deploy
      shell: bash
      env:
        MAVEN_CENTRAL_USER: ${{ inputs.user }}
        MAVEN_CENTRAL_PASSWORD: ${{ inputs.password }}
        GPG_PASSPHRASE: ${{ inputs.pgp-passphrase }}
        GPG_PUB_KEY: ${{ inputs.pgp-pub-key }}

    - name: "Deploy Staging"
      run: >
        mvn
        --batch-mode
        --no-transfer-progress
        --fail-at-end
        --show-version
        org.sonatype.plugins:nexus-staging-maven-plugin:1.6.13:deploy-staged-repository
        -DserverId=ossrh
        -DnexusUrl=https://oss.sonatype.org
        -DrepositoryDirectory=${{ github.workspace }}/temp_local_repo
        -DstagingProfileId="$MAVEN_CENTRAL_PROFILE_ID"
      shell: bash  
      env:
        MAVEN_CENTRAL_USER: ${{ inputs.user }}
        MAVEN_CENTRAL_PASSWORD: ${{ inputs.password }}
        MAVEN_CENTRAL_PROFILE_ID: ${{ inputs.profile }}
