name: Deploy to artifactory
description: "Deploys artifacts to artifactory."

inputs:
  repository-url:
    description: "The URL of the repository to upload to."
    required: true
  server-id:
    description: "The service id of the repository to upload to."
    required: true
  user:
    description: "The user used for the upload."
    required: true
  password:
    description: "The password used for the upload."
    required: true
  pom-file:
    description: "The path to the POM file."
    required: false
    default: "pom.xml"
  maven-version:
    description: "The Maven version the build shall run with."
    required: true

runs:
  using: composite
  steps:
    - name: Echo Inputs
      run: |
        echo "repository-url: ${{ inputs.repository-url }}"
        echo "user: ${{ inputs.user }}"
        echo "password: ${{ inputs.password }}"
        echo "pom-file: ${{ inputs.pom-file }}"
        echo "altDeploymentRepository: ${{inputs.server-id}}::${{inputs.repository-url}}"
      shell: bash

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: sapmachine
        java-version: '17'
        server-id: ${{ inputs.server-id }}
        server-username: DEPLOYMENT_USER
        server-password: DEPLOYMENT_PASS

    - name: Setup Maven ${{ inputs.maven-version }}
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: ${{ inputs.maven-version }}

    - name: Deploy
      run: >
        mvn -B -ntp -fae --show-version
        -pl !integration-tests,!integration-tests/db,!integration-tests/srv
        -DaltDeploymentRepository=${{inputs.server-id}}::${{inputs.repository-url}}
        -Dmaven.install.skip=true
        -Dmaven.test.skip=true
        -f ${{ inputs.pom-file }}
        deploy
      env:
        DEPLOYMENT_USER: ${{ inputs.user }}
        DEPLOYMENT_PASS: ${{ inputs.password }}
      shell: bash
