
---
spring:
  config:
    activate:
      on-profile: default
  sql:
    init:
      platform: h2
cds:
  security:
    mock:
      users:
        admin:
          password: admin
          roles:
          - admin
        user:
          password: user
  data-source:
    auto-config:
      enabled: false
---
spring:
  config:
    activate:
      on-profile: local-mtxs
cds:
  multi-tenancy:
    mtxs:
      enabled: true
    sidecar:
      url: http://localhost:4005
  security:
    mock:
      users:
        admin:
          password: admin
          tenant: t1
          roles:
          - admin
        user:
          password: user
          tenant: t1
        erin:
          password: erin
          tenant: t2
          roles:
          - admin
---
management:
  endpoint:
    health:
      show-components: always
      probes.enabled: true
  endpoints:
    web:
      exposure:
        include: health
  health:
    defaults.enabled: false
    ping.enabled: true
    db.enabled: true
