name: Scan with SonarQube
description: Scans the project with SonarQube

inputs:
  sonarq-token:
    description: The token to use for SonarQube authentication
    required: true
  github-token:
    description: The token to use for GitHub authentication
    required: true
  java-version:
    description: The version of Java to use
    required: true
  maven-version:
    description: The version of Maven to use
    required: true

runs:
  using: composite

  steps:
    - name: Set up Java ${{inputs.java-version}}
      uses: actions/setup-java@v5
      with:
        java-version: ${{inputs.java-version}}
        distribution: sapmachine
        cache: maven

    - name: Set up Maven ${{inputs.maven-version}}
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: ${{inputs.maven-version}}

    - name: Get Revision
      id: get-revision
      run: |
        echo "REVISION=$(mvn help:evaluate -Dexpression=revision -q -DforceStdout)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Print Revision
      run: echo "${{steps.get-revision.outputs.REVISION}}"
      shell: bash

    - name: Build project for SonarQube scan
      run: |
        mvn clean verify -ntp -B \
          -pl cds-feature-attachments,storage-targets/cds-feature-attachments-fs,storage-targets/cds-feature-attachments-oss \
          -am
      shell: bash

    - name: Verify JaCoCo reports exist
      run: |
        echo "=== Checking JaCoCo reports ==="
        find . -name "jacoco.xml" -type f
        for module in cds-feature-attachments storage-targets/cds-feature-attachments-fs storage-targets/cds-feature-attachments-oss; do
          if [ -f "$module/target/site/jacoco/jacoco.xml" ]; then
            echo "Found: $module/target/site/jacoco/jacoco.xml"
          else
            echo "Missing: $module/target/site/jacoco/jacoco.xml"
          fi
        done
      shell: bash

    - name: SonarQube Scan
      uses: SAP/project-piper-action@main
      with:
        step-name: sonarExecuteScan
        flags: >
          --token=${{ inputs.sonarq-token }}
          --githubToken=${{ inputs.github-token }}
          --version=${{ steps.get-revision.outputs.REVISION }}
          --inferJavaBinaries=true
          --options=-Dsonar.exclusions=**/samples/**,-Dsonar.coverage.jacoco.xmlReportPaths=cds-feature-attachments/target/site/jacoco/jacoco.xml,storage-targets/cds-feature-attachments-fs/target/site/jacoco/jacoco.xml,storage-targets/cds-feature-attachments-oss/target/site/jacoco/jacoco.xml