name: Scan Bookshop Sample with SonarQube
description: Scans the bookshop sample project with SonarQube

inputs:
  sonarq_token:
    description: The token to use for SonarQube authentication
    required: true
  github_token:
    description: The token to use for GitHub authentication
    required: true
  java_version:
    description: The version of Java to use
    required: true
  maven_version:
    description: The version of Maven to use
    required: true

runs:
  using: "composite"
  steps:
    - name: "Set up Java ${{ inputs.java_version }}"
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java_version }}
        distribution: "sapmachine"
        cache: "maven"

    - name: "Set up Maven ${{ inputs.maven_version }}"
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: ${{ inputs.maven_version }}

    - name: Install main cds-feature-attachments dependency
      shell: bash
      run: mvn install -ntp -B

    - name: Get Bookshop Revision
      id: get-revision
      shell: bash
      working-directory: samples/bookshop
      run: |
        echo "REVISION=$(mvn help:evaluate -Dexpression=revision -q -DforceStdout)" >> "$GITHUB_OUTPUT"

    - name: Print Bookshop Revision
      shell: bash
      run: echo "Bookshop revision: ${{ steps.get-revision.outputs.REVISION }}"

    - name: Build bookshop project with coverage
      shell: bash
      working-directory: samples/bookshop
      run: |
        mvn clean verify -ntp -B

    - name: Run SonarQube scan for bookshop
      shell: bash
      working-directory: samples/bookshop
      env:
        SONARQ_TOKEN: ${{ inputs.sonarq_token }}
        BOOKSHOP_REVISION: ${{ steps.get-revision.outputs.REVISION }}
      run: |
        mvn sonar:sonar \
          -Dsonar.host.url=https://sonar.tools.sap \
          -Dsonar.token="${SONARQ_TOKEN}" \
          -Dsonar.projectVersion="${BOOKSHOP_REVISION}"