name: Integration Tests with current version of CAP Java
description: Run integration tests with the current version of CAP Java using Maven.

inputs:
  java-version:
    description: The Java version the build shall run with.
    required: true
  maven-version:
    description: The Maven version the build shall run with.
    required: true

runs:
  using: composite
  steps:
    - name: Set up Java ${{ inputs.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: sapmachine
        cache: maven

    - name: Setup Maven ${{ inputs.maven-version }}
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: ${{ inputs.maven-version }}

    - name: Integration Tests with latest version of CAP Java
      run: mvn clean verify -ntp -B -f ./integration-tests/pom.xml -P latest-test-version
      shell: bash
