name: Label issues

permissions: {}

on:
  issues:
    types:
      - opened

jobs:
  label-issue:
    uses: cap-java/.github/.github/workflows/issue.yml@296573b55e906f5c77a1855bcfe4285cbbc5cac4 #main
