name: Label issues

permissions: {}

on:
  issues:
    types:
      - opened

jobs:
  label-issue:
    uses: cap-java/.github/.github/workflows/issue.yml@b5eb1ad6341e9fd1d681c42f3b36c4b750a7dac2 #main
