name: CI - PR

permissions:
  actions: read
  contents: read
  packages: read
  security-events: write

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [reopened, synchronize, opened]

jobs:
  build-and-test:
    uses: cap-java/cds-feature-attachments/.github/workflows/pipeline.yml@main
    secrets: inherit
