name: Prevent "New" Label on Issues

permissions: {}

on:
  issues:
    types: [labeled]

jobs:
  prevent-issue-labeling:
    uses: cap-java/.github/.github/workflows/prevent-issue-labeling.yml@296573b55e906f5c77a1855bcfe4285cbbc5cac4 #main
