name: Prevent "New" Label on Issues

permissions: {}

on:
  issues:
    types: [labeled]

jobs:
  guard:
    uses: cap-java/.github/.github/workflows/prevent-issue-labeling.yml@feat/centralized-actions-workflows
    permissions:
      issues: write
