name: Deploy to Maven Central

permissions: read-all

env:
  JAVA_VERSION: '17'
  MAVEN_VERSION: '3.9.12'

on:
  release:
    types: [ "released" ]

jobs:
  blackduck:
    name: Blackduck Scan
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Scan With Black Duck
        uses: ./.github/actions/scan-with-blackduck
        with:
          blackduck_token: ${{ secrets.BLACK_DUCK_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          maven-version: ${{ env.MAVEN_VERSION }}

  update-version:
    name: Update Version
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Update version
        uses: ./.github/actions/newrelease
        with:
          java-version: ${{ env.JAVA_VERSION }}
          maven-version: ${{ env.MAVEN_VERSION }}

      - name: Upload Changed Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: root-new-version
          path: .
          retention-days: 1

  build:
    name: Build and Sonar Scan
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: update-version
    env:
      AWS_S3_HOST: ${{ secrets.AWS_S3_HOST }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_S3_REGION: ${{ secrets.AWS_S3_REGION }}
      AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
      AWS_S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
      AZURE_CONTAINER_URI: ${{ secrets.AZURE_CONTAINER_URI }}
      AZURE_SAS_TOKEN: ${{ secrets.AZURE_SAS_TOKEN }}
      GS_BASE_64_ENCODED_PRIVATE_KEY_DATA: ${{ secrets.GS_BASE_64_ENCODED_PRIVATE_KEY_DATA }}
      GS_BUCKET: ${{ secrets.GS_BUCKET }}
      GS_PROJECT_ID: ${{ secrets.GS_PROJECT_ID }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: root-new-version

      - name: Build
        uses: ./.github/actions/build
        with:
          java-version: ${{ env.JAVA_VERSION }}
          maven-version: ${{ env.MAVEN_VERSION }}

      - name: Sonar Scan
        uses: ./.github/actions/scan-with-sonar
        with:
          java-version: ${{ env.JAVA_VERSION }}
          maven-version: ${{ env.MAVEN_VERSION }}
          sonarq-token: ${{ secrets.SONARQ_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Changed Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: root-build
          path: .
          retention-days: 1

  deploy:
    name: Deploy to Maven Central
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [blackduck, build]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: root-build

      - name: Deploy
        uses: ./.github/actions/deploy-release
        with:
          user: ${{ secrets.CENTRAL_REPOSITORY_USER }}
          password: ${{ secrets.CENTRAL_REPOSITORY_PASS }}
          pgp-pub-key: ${{ secrets.PGP_PUBKEY_ID }}
          pgp-private-key: ${{ secrets.PGP_PRIVATE_KEY }}
          pgp-passphrase: ${{ secrets.PGP_PASSPHRASE }}
          revision: ${{ github.event.release.tag_name }}
          maven-version: ${{ env.MAVEN_VERSION }}
