name: "Close stale issues"

permissions: {}

on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    uses: cap-java/.github/.github/workflows/stale.yml@5fc795c5049bb4d49e957346df2e5d6d7c0c23b9 #main
